version: '3'
services:
  #gogs-caddy:
  #  container_name: gogs-caddy
  #  image: abiosoft/caddy
  #  volumes:
  #    - "/xie/docker/gogs/caddy/Caddyfile:/etc/Caddyfile"
  #  restart: always
  collector:
    image: daocloud.io/94540413/play_data_collect_pi
    #deploy:
      #replicas: 1
      #resources:
      #  limits:
      #   cpus: "0.1"
      #    memory: 50M
      #restart_policy:
      #  condition: on-failure
    ports:
      - "13001:13001"
        #volumes:
        #- &:/
    restart: on-failure
