spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:file:/home/software/carprice/db/test;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 6666


img:
  downPath: /Users/zhao/Documents/tmp/carprice/imgs
  remoteAddress: http://www.yjysh.com/carloan/attachment/img/

carloan:
  removeApiAddress: http://192.168.10.103:10090/carloan/carPriceApi/orgzMap
