spring:
  profiles:
    active: dev   # java -jar carprice-0.0.1-SNAPSHOT.jar --spring.profiles.active=test
  thymeleaf:
    mode: LEGACYHTML5



# 远程关闭应用
endpoints:
  shutdown:
    enabled: true
    sensitive: true # 启动用户密码验证

# http://blog.csdn.net/cl_andywin/article/details/53992353
security:
  user:
    name: admin
    password: 12345678q
  basic:
    path: /shutdown,/prices/resetCarData,/prices/deleteCarData # 只有这个页面是需要安全验证的 其他不需要
    

# curl -u admin:12345678q -X POST http://localhost:7777/shutdown
management:
  port: 7777
  security:
    roles: SUPERUSER
server:
  context-path: /car

